/*
 * name:		nq_help.h
 *
 * desc:
 *
 * NQQS:
 *
 */
#ifndef __NQ_HELP_H
#define __NQ_HELP_H

// special categories
#define HELP_CAT_NONE			0
#define HELP_CAT_WEAPONS		0x00000001
#define HELP_CAT_SPAWNING		0x00000002
#define HELP_CAT_LOGGING		0x00000004
#define HELP_CAT_XP				0x00000008
#define HELP_CAT_CONFIGS		0x00000010
#define HELP_CAT_MESSAGES		0x00000020
#define HELP_CAT_FIELDOPS		0x00000040
#define HELP_CAT_MEDICS			0x00000080
#define HELP_CAT_ENGINEERS		0x00000100
#define HELP_CAT_SOLDIERS		0x00000200
#define HELP_CAT_COVERTOPS		0x00000400
#define HELP_CAT_ALLCLASSES		(HELP_CAT_SOLDIERS | HELP_CAT_MEDICS | HELP_CAT_ENGINEERS | HELP_CAT_FIELDOPS | HELP_CAT_COVERTOPS)
#define HELP_CAT_VOTING			0x00000800
#define HELP_CAT_DAMAGE			0x00001000
#define HELP_CAT_SEQURITY		0x00002000
#define HELP_CAT_WARMUP			0x00004000
#define HELP_CAT_PENALTY		0x00008000
#define HELP_CAT_SKILLS			0x00010000
#define HELP_CAT_BOTS			0x00020000
#define HELP_CAT_SERVER			0x00040000
#define HELP_CAT_TIME			0x00080000		// time/duration
#define HELP_CAT_DISTANCE		0x00100000
#define HELP_CAT_SHORTCUTS		0x00200000		// shrubbot shortcuts
#define HELP_CAT_LUA			0x00400000		// Lua
#define HELP_CAT_DEBUG			0x00800000		// debug vars (which might be only available on debug builds, or when cheats are enabled)
#define HELP_CAT_CHEAT			HELP_CAT_DEBUG	// ^^same as debug
#define HELP_CAT_PERFORMANCE	0x01000000
#define HELP_CAT_RESTRICT		0x02000000
// engine ?
// fireteams ?
#define HELP_CAT_DOCU			0x80000000	// do not change or remove this bitflag !..


#define HELP_NUM_LINES			20

typedef struct {
	char			*cvar;
	char			*defVal;
	unsigned int	categories;
	char			*line[HELP_NUM_LINES];
} helpText_t;



helpText_t helpTexts[] =
{
// special entry for shrubbot shortcuts documentation. There is no cvar for this, it's only text..
{"",									"",
										HELP_CAT_DOCU + HELP_CAT_SHORTCUTS,
										{"Shortcuts are codes to put in a chatline.",
										"The codes are replaced by the texts they represent.",
										"Here's the list of codes and their meaning:",
										"[a] = last ammo received from",
										"[b] = last teambleed by",
										"[c] = last teambleed damage",				// this damage was given by [b]
										"[d] = last player who killed you",
										"[f] = last player who called for ammo",	// most likely a teammate
										"[h] = last health received from",
										"[k] = last player you've killed",
										"[l] = location",
										"[m] = last player who called for medic",
										"[n] = your own name",
										"[p] = pointing at this player",
										"[r] = last revived/resuscitated by",
										"[s] = your own health",
										"[t] = your own ammo",
										"[w] = your own weapon",
										"[x] = last connected client",
										""}},

/*
{"sv_cheats",							"",
										HELP_CAT_SEQURITY + HELP_CAT_SERVER,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"gamename",							"nq",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"gamedate",							"",
										HELP_CAT_TIME,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"gamestate",							"-1",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"mod_version",							"1.3.0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"mod_url",								"http://shitstorm.org",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_restarted",							"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_reset",								"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_swapteams",							"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_balancedteams",						"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_axiswins",							"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_alliedwins",						"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_axismapxp",							"0",
										HELP_CAT_XP,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_alliedmapxp",						"0",
										HELP_CAT_XP,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_oldCampaign",						"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_currentCampaign",					"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_currentCampaignMap",				"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"voteFlags",							"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"sv_mapname",							"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
*/

// *************
// engine cvars
// *************
{"com_hunkmegs",						"56",
										HELP_CAT_SERVER, // HELP_CAT_CLIENT
										{"This option determines how much memory the server will use for players and items.",
										"Set this to a value of 128MB.",
										"This assumes no other applications are running in the background.",
										"If other server applications are running, you should expect to need more system RAM.",
										"",
										"For clients 80 MB is a good value.","","","","","","","","","","","","","",""}},
/*
{"com_soundmegs",						"32",
										HELP_CAT_NONE,
										{"...",
										"","","","","","","","","","","","","","","","","","",""}},

*/
{"sv_floodprotect",						"1",
										HELP_CAT_SERVER + HELP_CAT_RESTRICT,
										{"Prevents players from flooding the server usually with chat messages.",
										"","","","","","","","","","","","","","","","","","",""}},
// end engine cvars


{"ip_max_clients",						"3",
										HELP_CAT_SERVER + HELP_CAT_RESTRICT,
										{"Protective CVAR to prevent connection flooding attacks like q3fill.",
										"Limits the number of connections per IP.",
										"","","","","","","","","","","","","","","","","",""}},
/*
{"Players_Axis",						"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"Players_Allies",						"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"P",									"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"campaign_maps",						"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"C",									"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
*/
{"g_gametype",							"2",
										HELP_CAT_SERVER,
										{"Controls the type of gameplay.",
										 "Value 2: Objective",
										 "Value 3: Stop Watch",
										 "Value 4: Campaign",
										 "Value 5: Last Man Standing",
										 "Value 6: Map Voting - Note: Limit of maps to vote for is 32.",
										 "","","","","","","","","","","","","",""}},

{"g_countryflags",						"0",
										HELP_CAT_SERVER,
										{"Enable/Disable country flags system.",
										"You need a valid GeoIP.dat in your noquarter path of the server.",
										"This file can be downloaded from http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz and needs to be unpacked afterwards.",
										"You should read and accept the license of this database, see http://www.maxmind.com/download/geoip/database/LICENSE.txt.",
										"In case of problems check your logfiles. The GeoIP code will log errors in etconsole.log with a \"GeoIP\" prefix.",
										"","","","","","","","","","","","","","",""}},

{"g_maxlives",							"0",
										HELP_CAT_SPAWNING + HELP_CAT_RESTRICT,
										{"The maximum number of times a player can respawn.",
										"A value of 0 means: There is no limit.",
										"","","","","","","","","","","","","","","","","",""}},
{"g_maxlivesRespawnPenalty",			"0",
										HELP_CAT_SPAWNING + HELP_CAT_RESTRICT,
										{"Allows a player (who has lost all his lives) to",
										"respawn after a set number of deployment cycles.",
										"","","","","","","","","","","","","","","","","",""}},
{"g_alliedmaxlives",					"0",
										HELP_CAT_SPAWNING + HELP_CAT_RESTRICT,
										{"The maximum number of times an allied player can respawn.",
										"A value of 0 means: There is no limit.",
										"","","","","","","","","","","","","","","","","",""}},
{"g_axismaxlives",						"0",
										HELP_CAT_SPAWNING + HELP_CAT_RESTRICT,
										{"The maximum number of times an axis player can respawn.",
										"A value of 0 means: There is no limit.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_landminetimeout",					"1",
										HELP_CAT_WEAPONS + HELP_CAT_ENGINEERS,
										{"When enabled (value 1) and a player switches team, or disconnects,",
										"his planted landmines will be removed from the map.",
										"A value of 0 will leave the mines in the world.",
										"","","","","","","","","","","","","","","","",""}},

{"sv_maxclients",						"20",
										HELP_CAT_SERVER + HELP_CAT_PERFORMANCE + HELP_CAT_RESTRICT,
										{"Sets the maximum amount of available clients (slots) at the server.",
										"Note: Value set at sv_privateclients will be deducted from the max amount automatically.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_maxGameClients",					"0",
										HELP_CAT_NONE + HELP_CAT_RESTRICT,
										{"Max number of clients playing ingame (rest are stuck in spectator)? Also see team_maxplayers.",
										 "","","","","","","","","","","","","","","","","","",""}},
{"g_minGameClients",					"8",
										HELP_CAT_NONE + HELP_CAT_RESTRICT,
										{"Set to howmany clients must join a server before it enters restricted mode.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_redlimbotime",						"30000",
										HELP_CAT_SPAWNING + HELP_CAT_TIME,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_bluelimbotime",						"30000",
										HELP_CAT_SPAWNING + HELP_CAT_TIME,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_medicChargeTime",					"45000",
										HELP_CAT_MEDICS + HELP_CAT_TIME,
										{"Sets the charge time of medics.",
										"","","","","","","","","","","","","","","","","","",""}},
{"g_engineerChargeTime",				"30000",
										HELP_CAT_ENGINEERS + HELP_CAT_TIME,
										{"Sets the charge time of engineers.",
										"","","","","","","","","","","","","","","","","","",""}},
{"g_LTChargeTime",						"40000",
										HELP_CAT_FIELDOPS + HELP_CAT_TIME,
										{"Sets charge time of field ops.",
										"","","","","","","","","","","","","","","","","","",""}},
{"g_soldierChargeTime",					"20000",
										HELP_CAT_SOLDIERS + HELP_CAT_TIME,
										{"Sets charge time of soldiers.",
										"","","","","","","","","","","","","","","","","","",""}},
{"g_covertopsChargeTime",				"30000",
										HELP_CAT_COVERTOPS + HELP_CAT_TIME,
										{"Sets charge time of covert ops.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_csMethod",							"0",
										HELP_CAT_SERVER + HELP_CAT_PERFORMANCE,
										{"Sets the method used to handle the ConfigString data.",
										"Designed to get rid of the MAX_GAMESTATE_CHARS error on bigger servers.",
										"Default value is 0 for normal mode.",
										"Value 1 enables the new method.",
										"Note: This cvar is latched. (See also 'csMethod')",
										"The new setting will take effect on the next game-initializing (map-change or server-restart).",
										"","","","","","","","","","","","","",""}},

{"csMethod",							"",
										HELP_CAT_SERVER + HELP_CAT_PERFORMANCE,
										{"Reads the current method of handling ConfigString data.",
										"If the admin sets g_csMethod to a new value, it is not effective immediately.",
										"Not until the game enters the initializing phase, the new g_csMethod is used.",
										"To check the currently used method, this csMethod cvar is issued.",
										"This value is read-only.",
										"","","","","","","","","","","","","","",""}},

{"g_csStrings",							"3",
										HELP_CAT_SERVER + HELP_CAT_PERFORMANCE + HELP_CAT_RESTRICT,
										{"Sets the number of strings per packet.",
										"Used only csMethod 1 is active.",
										"Min/Max values: 1/15",
										"Note: If set to a higher value (than 3), some players may get problems.",
										"If players keep seeing 'Initalizing..' on screen, set this value back to the default of 3.",
										"Use this at Your own discretion and risk.",
										"","","","","","","","","","","","","",""}},

{"nq_scriptMode",						"7",
										HELP_CAT_SERVER + HELP_CAT_PERFORMANCE,
										{"Sets the use of old or new code for processing mapscript.",
										"Enable any bit to use the new (faster) code.",
										"Disable any bit to use old code.",
										"Bit 0 (Value 1): G_Script Preparse.",
										"Bit 1 (Value 2): G_RunEntity.",
										"Bit 2 (Value 4): G_Script_GetEventIndex.",
										"","","","","","","","","","","","","",""}},

{"skill_soldier",						"20 50 90 140 200 270 350 440 540",
										HELP_CAT_SOLDIERS + HELP_CAT_XP + HELP_CAT_SKILLS,
										{"Sets the amount of XP needed to succeed to the next skill level.",
										"","","","","","","","","","","","","","","","","","",""}},

{"skill_medic",							"20 50 90 140 200 270 350 440 540",
										HELP_CAT_MEDICS + HELP_CAT_XP + HELP_CAT_SKILLS,
										{"Sets the amount of XP needed to succeed to the next skill level.",
										"","","","","","","","","","","","","","","","","","",""}},

{"skill_engineer",						"20 50 90 140 200 270 350 440 540",
										HELP_CAT_ENGINEERS + HELP_CAT_XP + HELP_CAT_SKILLS,
										{"Sets the amount of XP needed to succeed to the next skill level.",
										"","","","","","","","","","","","","","","","","","",""}},

{"skill_fieldops",						"20 50 90 140 200 270 350 440 540",
										HELP_CAT_FIELDOPS + HELP_CAT_XP + HELP_CAT_SKILLS,
										{"Sets the amount of XP needed to succeed to the next skill level.",
										"","","","","","","","","","","","","","","","","","",""}},

{"skill_covertops",						"20 50 90 140 200 270 350 440 540",
										HELP_CAT_COVERTOPS + HELP_CAT_XP + HELP_CAT_SKILLS,
										{"Sets the amount of XP needed to succeed to the next skill level.",
										"","","","","","","","","","","","","","","","","","",""}},

{"skill_battlesense",					"20 50 90 140 200 270 350 440 540",
										HELP_CAT_XP + HELP_CAT_SKILLS,
										{"Sets the amount of XP needed to succeed to the next skill level.",
										"","","","","","","","","","","","","","","","","","",""}},

{"skill_lightweapons",					"20 50 90 140 200 270 350 440 540",
										HELP_CAT_XP + HELP_CAT_SKILLS,
										{"Sets the amount of XP needed to succeed to the next skill level.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_falloff",							"1",
										HELP_CAT_DAMAGE + HELP_CAT_DISTANCE,
										{"Sets the damage falloff over distance.",
										"Value 1: headshots only.",
										"Value 2: all hits.",
										"","","","","","","","","","","","","","","","",""}},

{"vote_limit",							"5",
										HELP_CAT_VOTING,
										{"Limit of votings per map and player (Not gametype 6).",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_percent",						"50",
										HELP_CAT_VOTING,
										{"Minimum of players having to vote 'YES', for a vote to pass.",
										"",
										"","","","","","","","","","","","","","","","","",""}},

{"vote_allow_comp",						"1",
										HELP_CAT_VOTING,
										{"Vote: Load competition settings.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_pub",						"1",
										HELP_CAT_VOTING,
										{"Vote: Load public settings.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_gametype",					"1",
										HELP_CAT_VOTING,
										{"Vote: Gametype.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_kick",						"1",
										HELP_CAT_VOTING + HELP_CAT_PENALTY,
										{"Vote: Kick a player.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_map",						"1",
										HELP_CAT_VOTING,
										{"Vote: Map.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_matchreset",				"1",
										HELP_CAT_VOTING,
										{"Vote: Match reset.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_mutespecs",				"1",
										HELP_CAT_VOTING,
										{"Vote: Mute spectators.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_nextmap",					"1",
										HELP_CAT_VOTING,
										{"Vote: Nextmap.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_referee",					"0",
										HELP_CAT_VOTING,
										{"Vote: Referee.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_shuffleteamsxp",			"1",
										HELP_CAT_VOTING + HELP_CAT_XP,
										{"Vote: Shuffle teams on XP.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_shuffleteamsxp_norestart",	"1",
										HELP_CAT_VOTING + HELP_CAT_XP,
										{"Vote: Shuffle teams on XP, no restart.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_swapteams",				"1",
										HELP_CAT_VOTING,
										{"Vote: Swap teams.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_friendlyfire",				"1",
										HELP_CAT_VOTING,
										{"Vote: Friendly fire.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_timelimit",				"0",
										HELP_CAT_VOTING,
										{"Vote: Timelimit.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_warmupdamage",				"1",
										HELP_CAT_VOTING + HELP_CAT_WARMUP,
										{"Vote: Warmup damage.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_antilag",					"1",
										HELP_CAT_VOTING,
										{"Vote: Antilag.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_balancedteams",			"1",
										HELP_CAT_VOTING,
										{"Vote: Balanced teams.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_muting",					"1",
										HELP_CAT_VOTING,
										{"Vote: Mute player.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_surrender",				"1",
										HELP_CAT_VOTING,
										{"Vote: Surrender.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_restartcampaign",			"1",
										HELP_CAT_VOTING,
										{"Vote: Restart campaign.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_nextcampaign",				"1",
										HELP_CAT_VOTING,
										{"Vote: Next campaign.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_poll",						"1",
										HELP_CAT_VOTING,
										{"Vote: Poll.",
										"","","","","","","","","","","","","","","","","","",""}},

{"vote_allow_maprestart",				"1",
										HELP_CAT_VOTING,
										{"Vote: Map restart.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_voting",							"0",
										HELP_CAT_VOTING,
										{"Set ingame voting options.",
										"Bit 0 (value 1): Use total voters instead of total players to decide if a vote passes.",
										"Bit 1 (value 2): Successful votes do not count against vote_limit",
										"Bit 2 (value 4): Append '(called by name)' in vote string",
										"","","","","","","","","","","","","","","",""}},

{"g_mapVoteFlags",						"0",
										HELP_CAT_VOTING,
										{"Map voting only! Vote flags to set behaviour during intermission.",
										"Bit 0  (value 1): Changes the tie breaker so that the map not played in the longest wins.",
										"Bit 1  (value 2): Intermission doesn't end until g_intermissionReadyPercent people have voted.",
										"Bit 2  (value 4): Enables multi voting. Allows everybody to vote for 3 maps instead of one,",
										"Bit 3  (value 8): Don't randomize the maps, so they will always appear in the same order.",
										"Bit 4 (value 16): A passed nextmap vote will restart the intermission and voting process.",
										"                  Note: This makes one of the two teams be displayed as winner.",
										"","","","","","","","","","","","",""}},

{"g_maxMapsVotedFor",					"6",
										HELP_CAT_VOTING,
										{"Map voting only! Count of shown maps to vote for.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_minMapAge",							"3",
										HELP_CAT_VOTING,
										{"Map voting only! Maps played until a map is ready to vote again.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_excludedMaps",						"",
										HELP_CAT_VOTING,
										{"Map voting only! Exclude maps from voting.",
										"Seperate the mapnames by : characters. Example: \":fueldump:oasis:\"",
										"","","","","","","","","","","","","","","","","",""}},

{"g_heavyWeaponRestriction",			"100",
										HELP_CAT_SOLDIERS + HELP_CAT_WEAPONS + HELP_CAT_RESTRICT,
										{"Sets the percentage of players that can use heavy weapons (in a team).",
										"Example: If set to a value of 50, only 50%% of all players can use a heavy weapon",
										"Default value: everybody can use heavy weapons, no restriction",
										"","","","","","","","","","","","","","","","",""}},

{"team_panzerRestriction",				"0",
										HELP_CAT_SOLDIERS + HELP_CAT_WEAPONS + HELP_CAT_RESTRICT,
										{"Sets the percentage of connected players needed to enable Panzerfaust/Bazooka.",
										"If set to 10, up to 10 percent of the players can use panzer.",
										"If the limit is hit during gameplay, panzer is dropped and the player is forced to use secondary weapon.",
										"","","","","","","","","","","","","","","","",""}},

{"team_maxPanzers",						"-1",
										HELP_CAT_SOLDIERS + HELP_CAT_WEAPONS + HELP_CAT_RESTRICT,
										{"Sets maximum number of panzerfaust/bazooka weapons per team.",
										"Value -1: unlimited panzerfaust/bazooka",
										"Value  0: Disable panzerfaust/bazooka",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxMG42s",						"-1",
										HELP_CAT_SOLDIERS + HELP_CAT_WEAPONS + HELP_CAT_RESTRICT,
										{"Sets maximum number of Mobile MG42/Browning weapons per team.",
										"Value -1: unlimited Mobile MG42/Browning",
										"Value  0: Disable Mobile MG42/Browning",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxFlamers",						"-1",
										HELP_CAT_SOLDIERS + HELP_CAT_WEAPONS + HELP_CAT_RESTRICT,
										{"Sets maximum number of flamethrower weapons per team.",
										"Value -1: unlimited flamethrower",
										"Value  0: Disable flamethrower",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxMortars",						"-1",
										HELP_CAT_SOLDIERS + HELP_CAT_WEAPONS + HELP_CAT_RESTRICT,
										{"Sets maximum number of mortar weapons per team.",
										"Value -1: unlimited mortar",
										"Value  0: Disable mortar",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxriflegrenades",				"-1",
										HELP_CAT_WEAPONS + HELP_CAT_ENGINEERS + HELP_CAT_RESTRICT,
										{"Sets maximum number of rifle-grenade weapons per team.",
										"Value -1: unlimited rifle-grenade",
										"Value  0: Disable rifle-grenade",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxVenoms",						"-1",
										HELP_CAT_SOLDIERS + HELP_CAT_WEAPONS + HELP_CAT_RESTRICT,
										{"Sets maximum number of Venom weapons per team.",
										"Value -1: unlimited Venom",
										"Value  0: Disable Venom",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxShotguns",					"-1",
										HELP_CAT_WEAPONS + HELP_CAT_FIELDOPS + HELP_CAT_ENGINEERS + HELP_CAT_RESTRICT,
										{"Sets maximum number of shotgun weapons per team.",
										"Value -1: unlimited shotgun",
										"Value  0: Disable shotgun",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxLMG",							"-1",
										HELP_CAT_WEAPONS + HELP_CAT_RESTRICT,
										{"Sets maximum number of light machine guns per team.",
										"Value -1: unlimited LMG",
										"Value  0: Disable LMG",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxLandmines",					"-1",
										HELP_CAT_WEAPONS + HELP_CAT_ENGINEERS + HELP_CAT_RESTRICT,
										{"Sets maximum number of landmines per team.",
										"Value -1: unlimited landmines",
										"Value  0: Disable landmines",
										"","","","","","","","","","","","","","","","",""}},

{"team_airstrikeTime",					"10",
										HELP_CAT_FIELDOPS + HELP_CAT_WEAPONS + HELP_CAT_TIME + HELP_CAT_RESTRICT,
										{"The time (in seconds) that must elapse between airstrikes strikes per team.",
										"","","","","","","","","","","","","","","","","","",""}},

{"team_artyTime",						"10",
										HELP_CAT_FIELDOPS + HELP_CAT_WEAPONS + HELP_CAT_TIME + HELP_CAT_RESTRICT,
										{"The time (in seconds) that must elapse between artillery strikes per team.",
										"","","","","","","","","","","","","","","","","","",""}},

{"team_maxSoldiers",					"-1",
										HELP_CAT_SOLDIERS + HELP_CAT_RESTRICT,
										{"The maximum number of soldiers in a team.",
										"Value -1: unlimited soldier",
										"Value  0: Disable soldier",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxMedics",						"-1",
										HELP_CAT_MEDICS + HELP_CAT_RESTRICT,
										{"The maximum number of medics in a team.",
										"Value -1: unlimited medic",
										"Value  0: Disable medic",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxEngineers",					"-1",
										HELP_CAT_ENGINEERS + HELP_CAT_RESTRICT,
										{"The maximum number of engineers in a team.",
										"Value -1: unlimited engineer",
										"Value  0: Disable engineer",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxFieldops",					"-1",
										HELP_CAT_FIELDOPS + HELP_CAT_RESTRICT,
										{"The maximum number of field-opses in a team.",
										"Value -1: unlimited field-ops",
										"Value  0: Disable field-ops",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxCovertops",					"-1",
										HELP_CAT_COVERTOPS + HELP_CAT_RESTRICT,
										{"The maximum number of covert-opses in a team.",
										"Value -1: unlimited covert-ops",
										"Value  0: Disable covert-ops",
										"(See also team_maxIsPercentage)",
										"","","","","","","","","","","","","","","",""}},

{"team_maxplayers",						"0",
										 + HELP_CAT_RESTRICT,
										{"The maximum number of players in a team.",
										"Value 0: unlimited players",
										"","","","","","","","","","","","","","","","","",""}},

{"team_maxIsPercentage",				"0",
										HELP_CAT_WEAPONS + HELP_CAT_SPAWNING + HELP_CAT_ALLCLASSES + HELP_CAT_RESTRICT,
										{"Indicate if the team_maxXXX cvar values are calculated as a percentage.",
										"When set to 0, team_maxWEAPON and team_maxCLASS cvars will be used as absolute values.",
										"Example:",
										"  When set to 1, and team_maxShotguns set to 20, while 10 players are on the server. A maximum of 20%% of the players (per team) can use a shotgun, which results in 10 players / 100%% * 20%% = 2 players per team.",
										"A value of 1: Use percentages for team_maxWEAPON values (like: team_maxShotguns etc.)",
										"A value of 2: Use percentages for team_maxCLASS values (like: team_maxSoldiers etc.)",
										"","","","","","","","","","","","","",""}},

{"team_nocontrols",						"0",
										HELP_CAT_RESTRICT,
										{"Locks/unlocks a player's team usage of commands.",
										"Value 1: Lock",
										"Value 0: Unlock",
										"","","","","","","","","","","","","","","","",""}},

{"g_unlockWeapons",						"0",
										HELP_CAT_WEAPONS + HELP_CAT_FIELDOPS + HELP_CAT_MEDICS + HELP_CAT_ENGINEERS + HELP_CAT_SOLDIERS + HELP_CAT_COVERTOPS + HELP_CAT_RESTRICT,
										{"Picking up weapons per class.",
										"Bit 0 (value 1):  Soldier can pickup any weapon.",
										"Bit 1 (value 2):  Medic can pickup any weapon.",
										"Bit 2 (value 4):  Engineer can pickup any weapon.",
										"Bit 3 (value 8):  FieldOps can pickup any weapon.",
										"Bit 4 (value 16): CovertOps can pickup any weapon.",
										"","","","","","","","","","","","","",""}},


{"g_teamDamageRestriction",				"0",
										HELP_CAT_DAMAGE + HELP_CAT_RESTRICT,
										{"Kick players that have this percentage of hits inflicted on a teammate.",
										"A minimum of g_minhits hits total is required before this is effective.",
										"Players can see their current stats by executng /damage in console.",
										"Note: Shrubbot flag '1' overrule this setting. (Player cannot be vote-kicked, vote-muted, or complained against.)",
										"","","","","","","","","","","","","","","",""}},

{"match_latejoin",						"1",
										HELP_CAT_NONE,
										{"Decide if players can join a game if it is already in progress.",
										"Value 0: Players are not allowed to join a game in progress",
										"Value 1: Players are allowed to join at any time",
										"","","","","","","","","","","","","","","","",""}},

{"match_minplayers",					"4",
										HELP_CAT_NONE,
										{"Minimum number of players needed to start a match.",
										"Used in votes during warmup: Ready or not.",
										"","","","","","","","","","","","","","","","","",""}},

{"match_mutespecs",						"0",
										HELP_CAT_NONE,
										{"Mute spectators when they want to speak to players in another (playing) team.",
										"","","","","","","","","","","","","","","","","","",""}},

{"match_readypercent",					"100",
										HELP_CAT_NONE + HELP_CAT_WARMUP,
										{"Percentage of players needed to start a match.",
										"Used in votes during warmup: Ready or not.",
										"","","","","","","","","","","","","","","","","",""}},

{"match_timeoutcount",					"3",
										HELP_CAT_NONE,
										{"Let's a team be able to pause/unpause a match.",
										"A team can issue 'match_timeoutcount' timeouts.",
										"","","","","","","","","","","","","","","","","",""}},

{"match_timeoutlength",					"180",
										HELP_CAT_TIME,
										{"The duration of a match timeout (in seconds).",
										"(See also: match_timeoutcount)",
										"","","","","","","","","","","","","","","","","",""}},

{"match_warmupDamage",					"1",
										HELP_CAT_WARMUP,
										{"Enables friendly fire during warmup.",
										"Note: Related vote vote_allow_warmupDamage allows to vote for:",
										"0 = None, 1 = Enemies and 2 = Everyone.",
										"With g_friendlyFire set to 1 (enabled) NQ allows real warmupdamage",
										"","","","","","","","","","","","","","","",""}},

{"g_warmup",							"30",
										HELP_CAT_WARMUP + HELP_CAT_TIME,
										{"The duration of the warmup (in seconds)",
										"Note: The minimum duration is 10 seconds.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_doWarmup",							"0",
										HELP_CAT_WARMUP,
										{"Do a warmup on map-changes.",
										"","","","","","","","","","","","","","","","","","",""}},
/*
{"g_warmupLatch",						"1",
										HELP_CAT_WARMUP,
										{"","","","","","","","","","","","","","","","","","","",""}},
*/
{"g_intermissionTime",					"60",
										HELP_CAT_TIME,
										{"Set the duration (in seconds) for which the end-of-game screens display before loading the next map.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_intermissionReadyPercent",			"100",
										HELP_CAT_NONE,
										{"The percentage of players who need to hit the 'READY' button,",
										"to move on to the next map without waiting 'g_intermissionTime' to run out.",
										"","","","","","","","","","","","","","","","","",""}},

{"server_motd0",						"^dNo Quarter",
										HELP_CAT_SERVER + HELP_CAT_MESSAGES,
										{"(1st) Message Of The Day",
										"","","","","","","","","","","","","","","","","","",""}},
{"server_motd1",						"",
										HELP_CAT_SERVER + HELP_CAT_MESSAGES,
										{"(2nd) Message Of The Day",
										"","","","","","","","","","","","","","","","","","",""}},
{"server_motd2",						"",
										HELP_CAT_SERVER + HELP_CAT_MESSAGES,
										{"(3rd) Message Of The Day",
										"","","","","","","","","","","","","","","","","","",""}},
{"server_motd3",						"",
										HELP_CAT_SERVER + HELP_CAT_MESSAGES,
										{"(4th) Message Of The Day",
										"","","","","","","","","","","","","","","","","","",""}},
{"server_motd4",						"",
										HELP_CAT_SERVER + HELP_CAT_MESSAGES,
										{"(5th) Message Of The Day",
										"","","","","","","","","","","","","","","","","","",""}},
{"server_motd5",						"",
										HELP_CAT_SERVER + HELP_CAT_MESSAGES,
										{"(6th) Message Of The Day",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_XPSave",							"0",
										HELP_CAT_XP,
										{"Sets flags for allowing per player XP saving between campaigns, rounds, etc.",
										"Bit 0 (value 1): Store XP when a client disconnects",
										"Bit 1 (value 2): Don't reset XP to the pre-map start values on a map restart, shuffle, etc.",
										"Bit 2 (value 4): Never ever reset xp",
										"Bit 3 (value 8): Force the disconnection of clients with the same GUID as the connecting client.",
										"  This is useful in saving the stored XP of players with unreliable network connections",
										"  since they should still get their stored XP even if reconnecting immediately with a new IP address.",
										"Default value: XP-save disabled",
										"","","","","","","","","","","",""}},

{"g_XPSaveFile",						"xpsave.cfg",
										HELP_CAT_XP,
										{"Sets the filename of your old xpsave.cfg that will be converted to new XP format upon starting the server.",
										"This file will be relative to your fs_game directory (much like g_shrubbot).",
										"","","","","","","","","","","","","","","","","",""}},

{"g_XPSaveDirectory",					"",
										HELP_CAT_XP,
										{"ABSOLUTE path to a new directory that will contain .xp files.",
										"This is required for XP save to work.",
										"Directory must be created before starting your server.",
										"The path must not be relative like other file CVARs are, meaning, not just a 'xpsave' value for this.",
										"On linux something like this will work: \'/home/ownername/.etwolf/servername/xpsave\' or \'/home/ownername/noquarter/xpsave\'.",
										"On Windows: \'C:\\path\\to\\file\\xpsave\'.",
										"Note: Test with a /rcon writexp command to confirm you have properly set this CVAR.",
										"","","","","","","","","","","","",""}},

{"g_XPSaveMaxAge",						"86400",
										HELP_CAT_XP + HELP_CAT_TIME,
										{"The number of seconds that must pass, without a connection from this player,"
										"before XPSave forgets their XP and skills.",
										"Default value: 1 day",
										"","","","","","","","","","","","","","","","",""}},

{"g_XPDecay",							"0",
										HELP_CAT_XP,
										{"Decays players' XP on the server when set to 1.",
										"This feature is mainly used with the g_XPSave 4 flag which allows XP to continue building forever.",
										"Bit 0 (value 1):   Enable XP Decay",
										"Bit 1 (value 2):   Do not decay a player's XP when they are disconnected from the server",
										"Bit 2 (value 4):   Do not decay a player's XP for the class they are currently playing",
										"Bit 3 (value 8):   Do not decay a player's XP while they are spectating",
										"Bit 4 (value 16):  Do not decay a player's XP during warmup/intermission",
										"Bit 5 (value 32):  Do not decay a player's XP when he/she is playing on a team",
										"Bit 6 (value 64):  Do not decay a player's Battle Sense XP when he/she is playing",
										"Bit 7 (value 128): Do not decay a player's Light Weapons XP when he/she is playing",
										"","","","","","","","","",""}},

{"g_XPDecayRate",						"0",
										HELP_CAT_XP,
										{"Sets the rate (in skill points per second) that XP skill points for EACH skill will decay when g_XPDecay is enabled.",
										"Example: Setting this to 0.2 would result in a player losing 12 points per minute IN ALL SKILLS,",
										"so up to 84XP per minute if the player has skill points for each skill.",
										"","","","","","","","","","","","","","","","",""}},

{"g_XPDecayFloor",						"0",
										HELP_CAT_XP,
										{"This is the minimum that any particular skill can be reduced to by g_XPDecay.",
										"Example: Setting this to 540.0 will ensure that no player will ever lose rank or skill levels due to g_XPDecay.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_maxXP",								"-1",
										HELP_CAT_XP,
										{"If a player reaches 'g_maxXP' XP, his/her XP score will be reset.",
										"Set to -1 to disable.",
										"Note: A value of 0 will have the same effect as disabling maxXP.",
										"","","","","","","","","","","","","","","","",""}},

{"g_lms_teamForceBalance",				"1",
										HELP_CAT_NONE,
										{"Prevents players joining a team that had more players during current LMS round.",
										 "","","","","","","","","","","","","","","","","","",""}},
{"g_lms_roundlimit",					"3",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_lms_matchlimit",					"2",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_lms_currentMatch",					"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_lms_lockTeams",						"0",
										HELP_CAT_NONE,
										{"Toggles locking teams during a round (LMS only).",
										 "","","","","","","","","","","","","","","","","","",""}},
{"g_lms_followTeamOnly",				"1",
										HELP_CAT_NONE,
										{"Wether players can only spectate teammates (LMS only).",
										 "","","","","","","","","","","","","","","","","","",""}},

{"g_log",								"",
										HELP_CAT_LOGGING + HELP_CAT_SERVER,
										{"The name of the log-file to use.",
										"This needs to be set to enable logging.",
										"","","","","","","","","","","","","","","","","",""}},
{"g_logChat",							"",
										HELP_CAT_LOGGING + HELP_CAT_SERVER,
										{"Sets the name of the chat log file.",
										"When nothing is set, chat log is disabled.",
										"","","","","","","","","","","","","","","","","",""}},
{"g_logSync",							"0",
										HELP_CAT_LOGGING + HELP_CAT_SERVER,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_logCrash",							"crash.log",
										HELP_CAT_LOGGING + HELP_CAT_SERVER,
										{"Sets the name of the crash log file.",
										"Default value is recommended.",
										"","","","","","","","","","","","","","","","","",""}},
{"g_logOptions",						"0",
										HELP_CAT_LOGGING + HELP_CAT_SERVER,
										{"Sets options for console log.",
										"Bit 0 (Value 1):     Server puts obituaries in chat.",
										"Bit 7 (Value 128):   Log the GUIDs.",
										"Bit 8 (Value 256):   Log all private messages.",
										"Bit 9 (Value 512):   Real time stamps (dvl).",
										"Bit 10 (Value 1024): Log the IP in case of LOGOPTS_GUID is set for ClientUserinfoChangedGUID, ClientConnect & ClientDisconnect. (Adds also player name to the log in some cases).",
										"","","","","","","","","","","","","",""}},
{"g_logAdmin",							"",
										HELP_CAT_LOGGING + HELP_CAT_SERVER,
										{"The name of the shrubbot log-file to use.",
										"This needs to be set to enable shrubbot logging.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_debugHitboxes",						"0",
										HELP_CAT_DEBUG + HELP_CAT_PERFORMANCE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_debugPlayerHitboxes",				"0",
										HELP_CAT_DEBUG + HELP_CAT_PERFORMANCE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_debugMove",							"0",
										HELP_CAT_DEBUG,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_debugDamage",						"0",
										HELP_CAT_DEBUG,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_debugAlloc",						"0",
										HELP_CAT_DEBUG,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_debugBullets",						"0",
										HELP_CAT_DEBUG + HELP_CAT_PERFORMANCE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_debugConstruct",					"0",
										HELP_CAT_DEBUG,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_debugSkills",						"0",
										HELP_CAT_DEBUG,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"developer",							"0",
										HELP_CAT_DEBUG,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_scriptDebug",						"0",
										HELP_CAT_DEBUG,
										{"Shows script debugging info. See also g_scriptDebugLevel.",
										"Value 0: Disabled",
										"Value 1: Enabled",
										"",
										"","","","","","","","","","","","","","","",""}},
{"g_scriptDebugLevel",					"0",
										HELP_CAT_DEBUG,
										{"Script debug level. Requires int.",
										 "","","","","","","","","","","","","","","","","","",""}},
{"g_scriptName",						"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_mapScriptDirectory",				"",
										HELP_CAT_CONFIGS + HELP_CAT_SERVER,
										{"Changes directory for custom mapscripts.",
										"Similar to ETPro's \"b_mapScriptsDirectory\".",
										"","","","","","","","","","","","","","","","","",""}},

{"g_weaponScriptsDir",					"",
										HELP_CAT_WEAPONS + HELP_CAT_SERVER,
										{"Defines the directory that weapon scripts will be placed into.",
										"This provides a way to edit weapons behavior in NQ.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_mapConfigs",						"",
										HELP_CAT_CONFIGS + HELP_CAT_SERVER,
										{"Allows you to execute a custom config file for each map.",
										"When set, it specifies the folder where your map config files are, relative to the server's noquarter directory ([path to noquarter dir]/<your directory>).",
										"The config file for a map has to be named the same as the map with the extension .cfg, for instance oasis.cfg .",
										"You should also create a default.cfg file which will be read before the map-specific config files.",
										"","","","","","","","","","","","","","","",""}},

{"g_customConfig",						"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_ForceCvarFile",						"",
										HELP_CAT_SERVER + HELP_CAT_RESTRICT,
										{"Sets the filename with forced cvars settings to be used.",
										"Put the file into fs_homepath. The file can contain forcecvar & sv_cvar commands and usually carries the .cfg extension. The extension must also be included in the given filename.",
										"If this cvar is set, the given file will be executed at every mapstart.",
										"All the settings will also be checked for the complete duration of a map.",
										"Some examples of entries in the file:",
										"  forcecvar r_wolffog 1",
										"  sv_cvar cl_maxpackets IN 20 100",
										"  sv_cvar m_pitch OUT -0.011 0.011",
										"","","","","","","","","","","",""}},

{"g_userTimeLimit",						"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_userAlliedRespawnTime",				"0",
										HELP_CAT_SPAWNING + HELP_CAT_TIME,
										{"Sets respawn time for the Allied team.",
										"Times are in milliseconds. (1 second = 1000 milliseconds).",
										"This will override any existing map settings.",
										"","","","","","","","","","","","","","","","",""}},

{"g_userAxisRespawnTime",				"0",
										HELP_CAT_SPAWNING + HELP_CAT_TIME,
										{"Sets respawn time for the Axis team.",
										"Times are in milliseconds. (1 second = 1000 milliseconds).",
										"This will override any existing map settings.",
										"","","","","","","","","","","","","","","","",""}},

{"g_spawntimeMinPlayers",				"0",
										HELP_CAT_SPAWNING,
										{"Sets the minimum number of players needed to have full (map default) spawntimes.",
										"If set to a value > 0, and there are fewer than g_spawntimeMinPlayers players playing, spawntimes get reduced automatically.",
										"Example: If set to a value of 10, and there are 5 people playing, the spawntimes get halfed (50%%).",
										"Example: If set to a value of 6, and there are 2 people playing, the spawntimes will be 33%% of the usual times.",
										"Note: This CVAR has no effect when g_useralliedrespawntime and/or g_useraxisrespawntime are used (often set in map-configs).",
										"Do not use g_useraxisrespawntime if you want to use flexible spawntimes for axis.",
										"Do not use g_useralliedrespawntime if you want to use flexible spawntimes for allies.",
										"","","","","","","","","","","","",""}},

{"nq_playerspawning",					"1",
										HELP_CAT_SPAWNING,
										{"Controls player spawning behavior.",
										"Bit 0 (Value 1): Players spawn at closest- or random-spawn location (Values 0 or 1 respectively).",
										"","","","","","","","","","","","","","","","","",""}},

{"pmove_fixed",							"0",
										HELP_CAT_SERVER,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"pmove_msec",							"8",
										HELP_CAT_SERVER + HELP_CAT_TIME,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_antilag",							"1",
										HELP_CAT_SERVER,
										{"Sets AntiLag.",
										"A value of 0: Disable antilag.",
										"A value of 1: Enables antilag by server time.",
										"A value of 2: Enables antilag by attack time.", // see G_HistoricalTraceBegin
										"","","","","","","","","","","","","","","",""}},

{"g_antiwarp",							"1",
										HELP_CAT_SERVER,
										{"Sets AntiWarp.",
										"A value of 0: Disables antiwarp.",
										"A value of 1: Enables (common) antiwarp.",
										"A value of 2: Enables NQ antiwarp",
										"We recommend value of 2 for low-ping servers/players. Clients will notice less extrapolating on player-movements (which shows on the lagometer).",
										"","","","","","","","","","","","","","",""}},

{"g_maxWarp",							"4",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_fixedphysics",						"0",
										HELP_CAT_SERVER,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_fixedphysicsfps",					"125",
										HELP_CAT_SERVER + HELP_CAT_TIME,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"sv_fps",								"20",
										HELP_CAT_SERVER + HELP_CAT_TIME,
										{"The server Frames Per Second.",
										"Note: It is highly unadvisable to change this value!",
										"","","","","","","","","","","","","","","","","",""}},

{"g_truePing",							"0",
										HELP_CAT_NONE,
										{"Use a number of ping-samples to get a better average ping value.",
										"Pings can fluctuate a lot, and trueping flattens out the peeks.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_skipCorrection",					"1",
										HELP_CAT_NONE,
										{"If enabled: In case a client is missing frames, his movements will be predicted.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_password",							"none",
										HELP_CAT_SEQURITY + HELP_CAT_SERVER,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_needpass",							"0",
										HELP_CAT_SEQURITY + HELP_CAT_SERVER,
										{"Used with g_password.",
										"If g_needpass is set to 1 then, client will need the password set with g_password to access server.",
										"","","","","","","","","","","","","","","","","",""}},
{"sv_privatepassword",					"",
										HELP_CAT_SEQURITY + HELP_CAT_SERVER,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"refereePassword",						"none",
										HELP_CAT_SEQURITY + HELP_CAT_SERVER,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_censor",							"",
										HELP_CAT_PENALTY + HELP_CAT_RESTRICT,
										{"A comma delimited string of words that will be censored from chat.",
										"","","","","","","","","","","","","","","","","","",""}},
{"g_censorNames",						"",
										HELP_CAT_PENALTY + HELP_CAT_RESTRICT,
										{"A comma delimited string of words that will be censored from player names.",
										"Note: Internally some bad user names are added by the system.",
										"","","","","","","","","","","","","","","","","",""}},
{"g_censorPenalty",						"1",
										HELP_CAT_PENALTY + HELP_CAT_RESTRICT,
										{"Sets the penalty for saying a word in the g_censor list.",
										"Bit 0 (Value 1):  Gib player.",
										"Bit 1 (Value 2):  Kick players with names containing words in g_censorNames.",
										"Bit 2 (Value 4):  Kill player, but don't gib (flag 1 has priority over this).",
										"Bit 3 (Value 8):  Auto-mute for g_censorMuteTime seconds.",
										"Bit 4 (Value 16): Lose 10 XP.",
										"Bit 5 (Value 32): Burn.",
										"Bit 6 (Value 64): Poison.",
										"","","","","","","","","","","",""}},
{"g_censorMuteTime",					"0",
										HELP_CAT_PENALTY + HELP_CAT_TIME + HELP_CAT_RESTRICT,
										{"When the value of g_censorPenalty contains flag 8, censored player will be muted for g_censorMuteTime seconds.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_complaintlimit",					"6",
										HELP_CAT_PENALTY + HELP_CAT_RESTRICT,
										{"The number of complaints that have to be filed before someone is kicked.",
										"","","","","","","","","","","","","","","","","","",""}},
{"g_ipcomplaintlimit",					"3",
										HELP_CAT_PENALTY + HELP_CAT_RESTRICT,
										{"Kicks player after complaints filed from this many IP's (different players).",
										 "","","","","","","","","","","","","","","","","","",""}},
{"g_disableComplaints",					"0",
										HELP_CAT_PENALTY + HELP_CAT_RESTRICT,
										{"Bitflag variable for disabling complaints for specified types of teamkill.",
										 "Bit 0 (Value 1): Mines",
										 "Bit 1 (Value 2): Airstrike/ffe",
										 "Bit 2 (Value 4): Mortar","","","","","","","","","","","","","","","",""}},

{"g_spawnInvul",						"3",
										HELP_CAT_SPAWNING + HELP_CAT_TIME,
										{"The number of seconds players will be invincible after they spawn.",
										"(See also: g_alliedSpawnInvul & g_axisSpawnInvul)",
										"","","","","","","","","","","","","","","","","",""}},
{"g_alliedSpawnInvul",					"0",
										HELP_CAT_SPAWNING + HELP_CAT_TIME,
										{"The number of seconds Allied players will be invincible after they spawn.",
										"This will override g_spawnInvul if not 0.",
										"","","","","","","","","","","","","","","","","",""}},
{"g_axisSpawnInvul",					"0",
										HELP_CAT_SPAWNING + HELP_CAT_TIME,
										{"The number of seconds Axis players will be invincible after they spawn.",
										"This will override g_spawnInvul if not 0.",
										"","","","","","","","","","","","","","","","","",""}},
/*
{"g_noAttackInvul",						"0",
										HELP_CAT_SPAWNING + HELP_CAT_DAMAGE,
										{"Removes a player's spawn shield if they start to attack before it wears off.",
										"","","","","","","","","","","","","","","","","","",""}},
*/
{"g_ammoCabinetTime",					"60000",
										HELP_CAT_TIME,
										{"The amount of time, in milliseconds seconds, that it takes for the ammo pack stand to recharge one pack.",
										"","","","","","","","","","","","","","","","","","",""}},
{"g_healthCabinetTime",					"10000",
										HELP_CAT_TIME,
										{"The amount of time, in milliseconds seconds, that it takes for the health pack stand to recharge one pack.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_dropHealth",						"0",
										HELP_CAT_MEDICS + HELP_CAT_PERFORMANCE + HELP_CAT_RESTRICT,
										{"Sets the amount of medpacks a Medic drops when killed.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_dropAmmo",							"0",
										HELP_CAT_FIELDOPS + HELP_CAT_PERFORMANCE + HELP_CAT_RESTRICT,
										{"Sets the amount of ammo packs a Field Ops drops when killed.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_minHits",							"6",
										HELP_CAT_DAMAGE,
										{"Minimum number of damaging hits required before calculating if player has reached g_teamDamageRestriction threshold.",
										"Flamethrower and landmine hits are adjusted similar to shrub.",
										"Medics get -2 hits for every revive.",
										"","","","","","","","","","","","","","","","",""}},

{"g_autoTempBan",						"0",
										HELP_CAT_PENALTY + HELP_CAT_RESTRICT,
										{"When set, anyone kicked for the reasons you specify, will be temporarily banned for g_autoTempBanTime seconds.",
										"Bit 0 (Value 1): Tempban when reaching g_teamDamageRestriction.",
										"Bit 1 (Value 2): Tempban when someone is kicked by a shrubbot admin (using the !kick command).",
										"Bit 2 (Value 4): Tempban when someone is kicked by the advanced warning system.",
										"","","","","","","","","","","","","","","",""}},
{"g_autoTempBanTime",					"1800",
										HELP_CAT_PENALTY + HELP_CAT_TIME + HELP_CAT_RESTRICT,
										{"The number of seconds kicked for when g_autoTempBan is set.",
										"","","","","","","","","","","","","","","","","","",""}},
{"g_banIPs",							"",
										HELP_CAT_PENALTY + HELP_CAT_RESTRICT,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_filterBan",							"1",
										HELP_CAT_PENALTY + HELP_CAT_RESTRICT,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_spectatorInactivity",				"0",
										HELP_CAT_PENALTY + HELP_CAT_TIME + HELP_CAT_RESTRICT,
										{"Time, in seconds, a spectator can stay inactive before he is kicked for inactivity.",
										"If enabled, a warning message is sent to the inactive spectator.",
										"See also g_inactivity",
										"","","","","","","","","","","","","","","","",""}},
{"g_inactivity",						"0",
										HELP_CAT_PENALTY + HELP_CAT_TIME + HELP_CAT_RESTRICT,
										{"Time, in seconds, a player can stay inactive (no moving and firing when he is not death) before he is moved to the spectators.",
										"If enabled, a warning message is sent to the inactive player.",
										"See also g_spectatorInactivity",
										"","","","","","","","","","","","","","","","",""}},

{"timelimit",							"0",
										HELP_CAT_TIME,
										{"Sets map/level time.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_nextTimeLimit",						"0",
										HELP_CAT_NONE,
										{"Used for stopwatch matches.",
										"","","","","","","","","","","","","","","","","","",""}},

{"nextmap",								"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"nextcampaign",						"",
										HELP_CAT_PERFORMANCE,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_campaignFile",						"",
										HELP_CAT_SERVER + HELP_CAT_CONFIGS + HELP_CAT_PERFORMANCE,
										{"Allows to set the name of used campaign file (typically dummy.campaign).",
										"This to prevent players to download every referenced pk3 on the server f.g. in objective mode.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_currentRound",						"0",
										HELP_CAT_NONE,
										{"Used for stopwatch and LMS matches.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_altStopwatchMode",					"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_customChat",						"1",
										HELP_CAT_MESSAGES,
										{"The number of succesive voice-chats allowed, before the spam protection becomes active.",
										"These are custom chat messages combined with a voice-command.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_voiceChatsAllowed",					"4",
										HELP_CAT_MESSAGES + HELP_CAT_RESTRICT,
										{"The number of succesive voice-commands allowed, before the spam protection becomes active.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_privateMessages",					"1",
										HELP_CAT_MESSAGES + HELP_CAT_RESTRICT,
										{"Allows players to send each other messages using /m playername message or /pm playername message.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_multikillTime",						"1000",
										HELP_CAT_TIME,
										{"The time, in milliseconds, that a player has to make another kill to be counted as a multikill.",
										"If g_multilkillTime milliseconds pass and a player does not make another kill, the multikill is announced and reset.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_announcer",							"127",
										HELP_CAT_MESSAGES,
										{"Enable or disable the announcer.",
										"Bit 0 (Value 1):   Announce killing sprees.",
										"Bit 1 (Value 2):   Announce death sprees.",
										"Bit 2 (Value 4):   Announce multikills.",
										"Bit 3 (Value 8):   Announce first blood.",
										"Bit 4 (Value 16):  Announce first headshot.",
										"Bit 5 (Value 32):  Announce kick sound.",
										"Bit 6 (Value 64):  Announce ban sound.",
										"Bit 7 (Value 128): Announce mission/objective info in the (left)pop-up area, instead of the default top-area.",
										"Bit 8 (Value 256): Disable mission/objective announcements.",
										"A value of 0 will disable the announcer.",
										"","","","","","","","",""}},

{"g_msgs",								"0",
										HELP_CAT_MESSAGES + HELP_CAT_TIME,
										{"Duration between banner messages setting g_msgX cvars, (g_msg1, g_msg2, etc.).",
										"The first missing g_msgX cvar will start the message cycle over, back to the first message.",
										"","","","","","","","","","","","","","","","","",""}},
{"g_msgpos",							"0",
										HELP_CAT_MESSAGES,
										{"Change the location of banner messages if g_msgs is non-zero and g_msgX cvars are set.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_constructiblexpsharing",			"0",
										HELP_CAT_XP + HELP_CAT_ENGINEERS,
										{"Building objectives gives XP to all engineers building an objective while you build it, rather than all at once when it is done.",
										"This is done to avoid that one engineer that spends a long time building something and then another engineer walks up and finishes it off gaining the XP for it.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_asblock",							"0",
										HELP_CAT_FIELDOPS + HELP_CAT_WEAPONS,
										{"Settings related to blocking air strike canisters.",
										"Bit 0 (Value 1): Make an announcement whenever an airstrike is blocked",
										"Bit 1 (Value 2): A player may easily block an airstrike by crouching, standing, or proning over the enemy's canister before the planes arrive",
										"Bit 2 (Value 4): Reserved",
										"Bit 3 (Value 8): Lvl 3 Field Ops and higher cannot have the airstrikes blocked by players",
										"","","","","","","","","","","","","","",""}},

{"g_canisterKick",						"0",
										HELP_CAT_FIELDOPS + HELP_CAT_WEAPONS + HELP_CAT_DISTANCE,
										{"Sets the scale of kicking grenades, airstike cans, and smoke cans.",
										"Set to 0 to disable.",
										"Value of around 60 - 80 is reasonable.",
										"Cans can be kicked with +kick command, no longer with +activate",
										"","","","","","","","","","","","","","",""}},

{"g_canisterKickOwner",					"0",
										HELP_CAT_FIELDOPS + HELP_CAT_WEAPONS,
										{"If canister kicking is set to a positive integer and g_canisterKickOwner is enabled,",
										"ownership of a grenade or airstrike changes to the last kicker",
										"","","","","","","","","","","","","","","","",""}},

{"g_doubleJump",						"0",
										HELP_CAT_NONE,
										{"Toggles double jumping",
										"A value of 0: Disable double jump.",
										"A value of 1: Enable double jump.",
										"A value of 2: Jaymod style double jump.",
										"","","","","","","","","","","","","","","",""}},

{"g_doubleJumpHeight",					"1.4",
										HELP_CAT_DISTANCE,
										{"Height boost gained by double jumping.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_goomba",							"10",
										HELP_CAT_DAMAGE,
										{"Players can damage each other by landing on each other.",
										"The value of g_goomba is a multiplier of how much damage is given.",
										"Setting this to 0 disables goombas.",
										"","","","","","","","","","","","","","","","",""}},

{"g_goombaFlags",						"25",
										HELP_CAT_DAMAGE,
										{"This is a bitflag cvar that controls the way g_goomba is handled.",
										"Bit 0 (Value 1):  Cannot goomba teammates.",
										"Bit 1 (Value 2):  Hopping on another player does no damage.",
										"Bit 2 (Value 4):  Hopping on a teammate does no damage.",
										"Bit 3 (Value 8):  Falling player recieves no damage when landing on any other player.",
										"Bit 4 (Value 16): Insta-gib goomba damage",
										"","","","","","","","","","","","","",""}},

{"g_missileSpeed",						"0",
										HELP_CAT_WEAPONS,
										{"Sets the speed a panzer/bazooka missile travels at.",
										"Set to 0 or 2500 to enable default speed.",
										"Values over 300 are ignored if Guided Rockets are enabled.",
										"","","","","","","","","","","","","","","","",""}},

{"g_missileHealth",						"5",
										HELP_CAT_WEAPONS + HELP_CAT_DAMAGE,
										{"Sets the amount of health a panzer/bazooka missile has.",
										"Set this to 0 to make missiles indestructible.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_missileGravity",					"0",
										HELP_CAT_WEAPONS,
										{"Sets gravity on Panzer and Bazooka rockets.",
										"Note: This is not a bitmask cvar.",
										"A value of 1: Strong gravity.",
										"A value of 2: Weak gravity (realistic).",
										"","","","","","","","","","","","","","","",""}},

{"g_shortcuts",							"0",
										HELP_CAT_MESSAGES + HELP_CAT_RESTRICT,
										{"Toggles shortcuts for player names, current health and other useful info. ",
										 "Note: This is not a bitmask cvar.",
										 "A value of 0: Disables shortcuts.",
										 "A value of 1: Enables Shortcuts .","","","","","","","","","","","","","","","",""}},

{"g_shrubbot",							"shrubbot.cfg",
										HELP_CAT_NONE,
										{"Sets the name of the shrubbot config file. When nothing is set, shrubbot features are disabled.",
										 "","","","","","","","","","","","","","","","","","",""}},

{"g_weapons",							"0",
										HELP_CAT_WEAPONS + HELP_CAT_FIELDOPS + HELP_CAT_MEDICS + HELP_CAT_ENGINEERS + HELP_CAT_RESTRICT,
										{"Various flags to set different weapon behaviors:",
										"Bit 0 (Value 1):  Field Ops do not spawn with binoculars if they have level 0 Battle Sense.",
										"Bit 1 (Value 2):  Syringes work underwater.",
										"Bit 2 (Value 4):  Pliers work underwater.",
										"Bit 3 (Value 8):  \"Too many airstrikes requested/Insufficient fire support\" will restore used charge bar.",
										"Bit 4 (Value 16): \"Too many airstrikes requested/Insufficient fire support\" will restore half of used charge bar.",
										"Bit 5 (Value 32): Restore lost helmets with ammo packs.",
										"","","","","","","","","","","","",""}},

{"g_teamChangeKills",					"1",
										HELP_CAT_NONE,
										{"Switching teams kills the player.",
										"This does not apply to spectators joining a team.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_playDead",							"0",
										HELP_CAT_RESTRICT,
										{"Allows players to use the /playdead command.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_shove",								"80",
										HELP_CAT_DISTANCE + HELP_CAT_RESTRICT,
										{"This sets the distance players can shove each other by going up to another player and hitting the activate key (f by default).",
										"80 is a decent value.",
										"Set to 0 to disable shoving.",
										"","","","","","","","","","","","","","","","",""}},

{"g_shoveNoZ",							"0",
										HELP_CAT_DISTANCE + HELP_CAT_RESTRICT,
										{"Toggle shoving in vertical direction.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_dragCorpse",						"1",
										HELP_CAT_RESTRICT,
										{"Toggles corpse dragging.",
										"When enabled, players can drag wounded teammates to safety by holding the activate key grab the corpse, then move it to where you want using your movement keys.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_dropObj",							"0",
										HELP_CAT_RESTRICT,
										{"Sets the number of times a player can drop/toss the objective per life.",
										"Objectives can be dropped by switching to the knife pressing the activate key.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_knockback",							"1000",
										HELP_CAT_DISTANCE,
										{"Sets how much a player's position is affected after being hit by a projectile.",
										"It also affects foot-kicking.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_friendlyFire",						"1",
										HELP_CAT_DAMAGE + HELP_CAT_RESTRICT,
										{"Options for friendly fire:",
										"To enable friendly fire, flag 1 is required.",
										"Bit 0 (Value 1):  Enable friendly fire.",
										"Bit 1 (Value 2):  Friendly fire does only half damage to teammates.",
										"Bit 2 (Value 4):  Friendly fire does an equal amount of damage to the inflictor.",
										"Bit 3 (Value 8):  Friendly fires affects movers (tanks, trucks, etc).",
										"Bit 4 (Value 16): Friendly fire delivers knockback (useful for kicking teammates or grenade boosting).",
										"Bit 5 (Value 32): Landmines cannot be tripped by teammates.",
										"Bit 6 (Value 64): Landmines hurt teammates when friendly fire is disabled.",
										"","","","","","","","","","",""}},

{"g_forcerespawn",						"0",
										HELP_CAT_SPAWNING + HELP_CAT_TIME,
										{"Sets the respawn time in seconds.",
										"A value of 0: don't force respawn.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_filtercams",						"0",
										HELP_CAT_RESTRICT,
										{"Sets the visibility of players & corpses in Limbo Objective Cams.",
										"A value of 0: disable filter, see all players & corpses.",
										"A value of 1: enable filter, hide all players & corpses.",
										"","","","","","","","","","","","","","","","",""}},

{"g_slashKill",							"0",
										HELP_CAT_RESTRICT,
										{"This is a bitflag cvar that controls various options and consequences for suicide by /kill cmd.",
										"Bit 0 (Value 1):   Player spawns with half charge bar after /kill.",
										"Bit 1 (Value 2):   Player spawns with 0 charge bar after /kill.",
										"Bit 2 (Value 4):   Restores the charge bar to the same state it was in at the moment the player issued /kill (regardless of how long they were in limbo), (sticky charge).",
										"Bit 3 (Value 8):   Disables /kill command.",
										"Bit 4 (Value 16):  Disable /kill when player is poisoned.",
										"Bit 5 (Value 32):  While in limbo after a /kill, charge bar fills normally.",
										"Bit 6 (Value 64):  Disables /kill while in a fight.",
										"Bit 7 (Value 128): Disables /kill while player is frozen.",
										"","","","","","","","","","",""}},

{"g_noAttacklInvul",					"0",
										HELP_CAT_DAMAGE,
										{"Removes spawn shield from a player once they begin to attack.",
										"","","","","","","","","","","","","","","","","","",""}},


{"g_fastBackStab",						"0",
										HELP_CAT_DAMAGE + HELP_CAT_RESTRICT,
										{"Backstabs insta-gibs players into limbo, making them unrevivable.",
										"Will play a unique animation on the stabbed player.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_hitsounds",							"1",
										HELP_CAT_MESSAGES,
										{"Toggles hitsounds regardless of client settings.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_weaponItems",						"1",
										HELP_CAT_WEAPONS,
										{"Customize how weapons are dropped upon limbo death:",
										"Bit 0 (Value 1):  Drop primary weapon upon limbo death (default ET).",
										"Bit 1 (Value 2):  Drops secondary weapons (pistols) upon limbo death.",
										"Bit 2 (Value 4):  Extra clips are included when you pickup a dropped weapon.",
										"Bit 3 (Value 8):  Pick up ammo you need from dropped weapons, but leave the gun and what ammo is left on the ground.",
										"Bit 4 (Value 16): Do not pickup dropped weapons you don't need, empty guns that you already have, or if you have full ammo.",
										"Bit 5 (Value 32): Do not pick up ammo clips from dropped Garands.",
										"A value of 0 will disable dropping of weapons upon limbo death.",
										"","","","","","","","","","","",""}},

{"g_skills",							"0",
										HELP_CAT_SKILLS + HELP_CAT_RESTRICT,
										{"Allows players to retain skill bonuses when playing other classes.",
										"Bit 0 (Value 1):  Flak Jacket carries over.",
										"Bit 1 (Value 2):  unused.",
										"Bit 2 (Value 4):  Enemy recognition carries over.",
										"Bit 3 (Value 8):  Assassin backstab bonus carries over.",
										"Bit 4 (Value 16): Landmine spotting ability carries over.",
										"","","","","","","","","","","","","",""}},

{"jp_insanity",							"0",
										HELP_CAT_SPAWNING + HELP_CAT_WEAPONS + HELP_CAT_SOLDIERS + HELP_CAT_ENGINEERS + HELP_CAT_DAMAGE + HELP_CAT_MESSAGES + HELP_CAT_PERFORMANCE,
										{"No Quarter fun modes are controlled by this bitmask CVAR.",
										"Bit 0 (Value 1):      Instant Spawn.",
										"Bit 1 (Value 2):      Unlimited Ammo.",
										"Bit 2 (Value 4):      Mortar Cam.",
										"Bit 3 (Value 8):      Rocket Cam.",
										"Bit 4 (Value 16):     Unlimited Charge.",
										"Bit 5 (Value 32):     Guided Rockets.",
										"Bit 6 (Value 64):     Homing Rockets.",
										"Bit 7 (Values 128):   Dog Tags.",
										"Bit 8 (Values 256):   Venom Mode.",
										"Bit 9 (Values 512):   Shows attackers HP left message.",
										"Bit 10 (Values 1024): Shows attackers HP left message & distance.",
										"Bit 11 (Values 2048): Kickable Dynamite.",
										"Bit 12 (Values 4096): Killer Cam.",
										"Bit 13 (Values 8192): Riflenade Cam.",
										"","","","",""}},

{"nq_War",								"0",
										HELP_CAT_WEAPONS,
										{"No Quarter War Mode.",
										"Bit 0 (Value 1):      Enable warmode",
										"Bit 1 (Value 2):      Reserved (not in use)",
										"Bit 2 (Value 4):      Knives",
										"Bit 3 (Value 8):      Panzers",
										"Bit 4 (Value 16):     Sniperguns",
										"Bit 5 (Value 32):     Grenades",
										"Bit 6 (Value 64):     Riflenades",
										"Bit 7 (Values 128):   Flamethrowers",
										"Bit 8 (Values 256):   Shotguns",
										"Bit 9 (Values 512):   Poison",
										"Bit 10 (Values 1024): Smoke Grenades",
										"Bit 11 (Values 2048): Binoculars",
										"Bit 12 (Values 4096): Pliers + Dynamite",
										"","","","","",""}},

{"g_weaponBounce",						"0.25",
										HELP_CAT_WEAPONS + HELP_CAT_DISTANCE,
										{"Bounciness of dropped weapons.",
										 "","","","","","","","","","","","","","","","","","",""}},

{"g_throwDistance",						"75",
										HELP_CAT_WEAPONS + HELP_CAT_DISTANCE,
										{"The distance from the player that ammo and health packs are tossed.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_realHead",							"1",
										HELP_CAT_DAMAGE,
										{"Head hitbox will follow the animation that is played, just like ETPro.",
										"This is HIGHLY recommended.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_bulletReflect",						"0",
										HELP_CAT_WEAPONS + HELP_CAT_PERFORMANCE,
										{"Shooting at metal surfaces will reflect the bullets back at the appropriate angle.",
										"A value of 0: Disable bullet reflection.",
										"A value of 1: Reflect weapons that are set to reflect bullets.",
										"A value of 2: Reflect all weapons.",
										"","","","","","","","","","","","","","","",""}},

{"g_headshot",							"0",
										HELP_CAT_DAMAGE,
										{"Enables headshot mode.",
										"Only headshots from weapons that can make headshots will damage players. Explosions, MG's, shotguns, knives, goomba's, etc. will cause no damage.",
										"A value of 0: Disable headshot mode.",
										"A value of 1: Still multiple headshots are needed to kill. A headshot inflicts normal damage, bodyshots do no damage at all.",
										"A value of 2: A single headshot kills instantly, bodyshots do no damage at all.",
										"A value of 3: A single headshot kills instantly, bodyshots inflict normal damage.",
										"","","","","","","","","","","","","",""}},

{"g_spectator",							"0",
										HELP_CAT_NONE,
										{"Sets flags for various spectator options.",
										"Bit 0 (Value 1): Players will have a team coloured glow around them (red=Axis, blue=Allies).",
										"Bit 1 (Value 2): Players will have their names shown above them.",
										"","","","","","","","","","","","","","","","",""}},

{"g_realism",							"96",
										HELP_CAT_WEAPONS + HELP_CAT_PERFORMANCE + HELP_CAT_RESTRICT,
										{"A few flags to add a bit of realism to the gameplay.",
										"Bit 0 (Value 1):   Play transition animations when going into prone and standing up, overall it slows standing up from proning drastically.",
										"Bit 1 (Value 2):   Cannot use weapons while holding onto ladders.",
										"Bit 2 (Value 4):   Besides stealing the uniform, a covertops also inherits that players' head.",
										"Bit 3 (Value 8):   Enable 'in view' check for aura. Aura skills are only active when players can see each other. Do not activate on poor CPU servers or with high player count on the server!",
										"Bit 4 (Value 16):  Disable leaning.",
										"Bit 5 (Value 32):  No auto switching for poisoned players.",
										"Bit 6 (Value 64):  A script_mover removes items (when driving over them), instead of pushing the items.",
										"Bit 7 (Value 128): Players rotate along on a rotating mover.",
										"Bit 8 (Value 256): Changing view (look left/right) does not increase spread.",
										"Bit 9 (Value 512): Open (rotating) doors that are already closing.",
										"","","","","","","","",""}},

{"g_tyranny",							"1",
										HELP_CAT_NONE,
										{"This cvar controls the use of administrator commands that could be used by admins to cheat or abuse players.",
										"If it is set to 0 you will not be able to use commands on your server such as !gib, !slap, !burn, !poison, etc.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_fear",								"2000",
										HELP_CAT_TIME,
										{"Credit given to a player when and opponent uses /kill within g_fear milliseconds.",
										"Set to 0 to disable.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_medics",							"65",
										HELP_CAT_MEDICS + HELP_CAT_DAMAGE + HELP_CAT_RESTRICT,
										{"Medic bitflags:",
										"Bit 0 (Value 1):     Medics can't pick up their own med packs to heal poisoning.",
										"Bit 1 (Value 2):     Medics can't pick up their own med packs at all.",
										"Bit 2 (Value 4):     Medics regenerate at 2/1 instead of 3/2.",
										"Bit 3 (Value 8):     Medics regenerate at 1/0 instead of 1/0.",
										"Bit 4 (Value 16):    Medics can't get akimbos.",
										"Bit 5 (Value 32):    Medics can't carry SMG, nor pick one up.",
										"Bit 6 (Value 64):    Alternative to tk/revive for medics.",
										"Bit 7 (Value 128):   Medics get 12%% extra HP.",
										"Bit 8 (Value 256):   More Medics in a team do NOT make the team get higher maxHP.",
										"Bit 9 (Value 512):   Medics do not at all regenerate.",
										"Bit 10 (Value 1024): Medics get HP if (non-medic)teammates pickup their healthpack(s).",
										"Bit 11 (Value 2048): The maxHP of all players is independent of # medics in a team, all players have the 25 extra HP.",
										"Bit 12 (Value 4096): Fast medic resuscitationing.",
										"","","","","",""}},

{"g_adrenaline",						"0",
										HELP_CAT_ALLCLASSES + HELP_CAT_WEAPONS + HELP_CAT_DAMAGE + HELP_CAT_RESTRICT,
										{"Adrenaline-behavior bitflags:",
										"Bit 0 (Value 1):     Spawn with no adrenaline needles, can only get them from ammo packs.",
										"Bit 1 (Value 2):     Ammo packs do not contain adrenaline needles.",
										"Bit 2 (Value 4):     Can only carry one needle at a time.",
										"Bit 3 (Value 8):     Adrenaline does not boost health.",
										"Bit 4 (Value 16):    Adrenaline does not boost stamina.",
										"Bit 5 (Value 32):    Adrenaline causes player's eyes to glow red when used.",
										"Bit 6 (Value 64):    Health packs cannot be picked up while using adrenaline.",
										"Bit 7 (Value 128):   Enables adrenaline for soldier.",
										"Bit 8 (Value 256):   Enables adrenaline for medic.",
										"Bit 9 (Value 512):   Enables adrenaline for engineer.",
										"Bit 10 (Value 1024): Enables adrenaline for fieldops.",
										"Bit 11 (Value 2048): Enables adrenaline for covertops.",
										"Bit 12 (Value 4096): While using adrenaline you receive only half the damage.",
										"","","","",""}},
/*
{"cg_letterbox",						"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"dedicated",							"0",
										HELP_CAT_SERVER,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"server_autoconfig",					"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"z_serverflags",						"0",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
*/
{"URL",									"",
										HELP_CAT_SERVER + HELP_CAT_PERFORMANCE,
										{"Appears to simply be a place to locate the server's URL.",
										 "","","","","","","","","","","","","","","","","","",""}},

{"g_userAim",							"1",
										HELP_CAT_NONE,
										{"If set to 1, aim spreadScale will depend on a players view-movements.",
										"If set to 0, aim spreadScale is disabled.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_speed",								"320",
										HELP_CAT_DISTANCE,
										{"Sets the speed of players.",
										 "","","","","","","","","","","","","","","","","","",""}},
{"g_gravity",							"800",
										HELP_CAT_NONE,
										{"Sets the strengh of gravity.",
										 "","","","","","","","","","","","","","","","","","",""}},

{"g_moverScale",						"1.0",
										HELP_CAT_NONE,
										{"The speed factor for script_movers.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_movespeed",							"76",
										HELP_CAT_DISTANCE,
										{"","","","","","","","","","","","","","","","","","","",""}},

{"g_flushItems",						"1",
										HELP_CAT_NONE,
										{"Allows dropped items to lay flush with the angle of the ground they are on.",
										"May cause items to turn when they hit the ground.",
										"","","","","","","","","","","","","","","","","",""}},

{"g_mortarBBox",						"0",
										HELP_CAT_SOLDIERS + HELP_CAT_WEAPONS,
										{"Puts a bounding box (hitbox) around mortar shells, to prevent them from going through small windows and other narrow gaps.",
										"","","","","","","","","","","","","","","","","","",""}},

{"g_noTeamSwitching",					"0",
										HELP_CAT_NONE,
										{"Wether to disallow teams from swapping between teams.",
										 "","","","","","","","","","","","","","","","","","",""}},

{"g_teamForceBalance",					"0",
										HELP_CAT_RESTRICT,
										{"Toggles disallowing players from joining teams with more players.",
										 "","","","","","","","","","","","","","","","","","",""}},

{"g_enforcemaxlives",					"1",
										HELP_CAT_NONE,
										{"Player's who quit during a round cannot reconnect until the next round. For one life servers, works by IP",
										 "","","","","","","","","","","","","","","","","","",""}},

{"g_autoFireteams",						"1",
										HELP_CAT_NONE,
										{"Toggles automatically putting players into fireteams.",
										 "","","","","","","","","","","","","","","","","","",""}},

{"g_classChange",						"0",
										HELP_CAT_COVERTOPS + HELP_CAT_SPAWNING + HELP_CAT_RESTRICT,
										{"Toggles class switching.",
										"This allows players to steal a teammate's uniform, to switch to their class, gaining their class specific tools and abilities.",
										"Bit 0 (Value 1): Enables/disables class change.",
										"Bit 1 (Value 2): Keeps the class on spawn after class change (bit 0 needs to be set!).",
										"","","","","","","","","","","","","","","",""}},

{"g_forceLimboHealth",					"75",
										HELP_CAT_DAMAGE + HELP_CAT_SPAWNING,
										{"Sets the amount of health a wounded player has before they are forced into limbo (gibbed).",
										"WARNING: this CVAR behaves differently from ETPub. ETPub uses this as a boolean, so using your ETPub config without changing this, will cause wounded players to have 0 or 1 HP, meaning they will not be very revivable and often be insta-gibbed.",
										"","","","","","","","","","","","","","","","","",""}},
/*
{"g_synchronousClients",				"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
{"g_multiview",							"",
										HELP_CAT_NONE,
										{"","","","","","","","","","","","","","","","","","","",""}},
*/
{"omnibot_path",						"",
										HELP_CAT_BOTS,
										{"The path to the directory containing omnibot_et binary file.",
										"","","","","","","","","","","","","","","","","","",""}},

{"omnibot_enable",						"0",
										HELP_CAT_BOTS,
										{"Enables Omni-Bot.",
										"Call '(rcon) bot help' for all Omni-Bot commands.",
										"","","","","","","","","","","","","","","","","",""}},

{"omnibot_playing",						"0",
										HELP_CAT_BOTS,
										{"The number of playing bots (total of both teams).",
										"Var is set by system!",
										"","","","","","","","","","","","","","","","","",""}},

{"omnibot_flags",						"0",
										HELP_CAT_BOTS,
										{"Various flags affecting the behaviour of bots.",
										"Bit 0 (Value 1):  Disable XPSave for bots.",
										"Bit 1 (Value 2):  Bots cannot mount tanks.",
										"Bit 2 (Value 4):  Bots cannot mount emplaced guns.",
										"Bit 3 (Value 8):  Don't count bots (this affects the value of the cvar 'omnibot_playing' which contains the number of bots playing or -1 if this flag is set).",
										"Bit 4 (Value 16): Bots will gib dead players, so they can no longer be revived.",
										"Bit 5 (Value 32): Bots will trigger team and spotted mines.",
										"Bit 6 (Value 64): Bots can use g_shove.",
										"","","","","","","","","","","",""}},

{"g_allowBotSwap",						"0",
										HELP_CAT_BOTS + HELP_CAT_DEBUG,
										{"Allows to swap location with a bot.",
										 "Note: Only available in debug builds.",
										 "","","","","","","","","","","","","","","","","",""}},

{"g_simpleBullets",						"0",
										HELP_CAT_PERFORMANCE,
										{"Enables or disables simple bullets.",
										"Simple bullets is a new method for handling bullets, designed to produce faster code.",
										"This option does not affect accuracy in any way.",
										"","","","","","","","","","","","","","","","",""}},

{"g_killerLockTime",					"0",
										HELP_CAT_TIME,
										{"Enables the Killer-View-Locking.",
										"The Killer-Cam will lock the view of a dead player on his last killer.",
										"The medic-view-locking always overrules this killer-view-locking.",
										"Set this cvar to the duration (in seconds) that the cam should stay active.",
										"Any value < 1 will disable the Killer-Cam.",
										"The maximum value is 20.",
										"","","","","","","","","","","","","",""}},

{"lua_modules",							"",
										HELP_CAT_SERVER + HELP_CAT_LUA,
										{"See http://wolfwiki.anime.net/index.php/Lua_Mod_API",
										"Example: \"dc.lua NOQ.lua\"",
										"","","","","","","","","","","","","","","","","",""}},
{"lua_allowedModules",					"",
										HELP_CAT_SERVER + HELP_CAT_LUA,
										{"See http://wolfwiki.anime.net/index.php/Lua_Mod_API",
										"","","","","","","","","","","","","","","","","","",""}}
};

#endif
